// Browser interaction checks. All writes and observation streams are intercepted fixtures.
// NODE_PATH=.preview-tools/node_modules node scripts/check_web_workspace.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {chromium} = require('playwright');
const base=process.env.AGENTSPACE_PREVIEW_URL || 'http://127.0.0.1:7790';
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[], writes=[];page.on('pageerror',e=>errors.push(e.message));
 fs.mkdirSync('.preview-artifacts',{recursive:true});
 // Deny unrecognized writes; successful writes below are synthetic and never reach the server.
 await page.route('**/*',async route=>{
   const req=route.request(),url=new URL(req.url());
   if(req.method()==='POST') {
     const fields=new URLSearchParams(req.postData()||'');writes.push({path:url.pathname,fields:Object.fromEntries(fields)});
     if(url.pathname==='/new/pd/build')return route.fulfill({json:{id:'fixture-build'}});
     if(url.pathname==='/run/snap/fork')return route.fulfill({json:{id:'fixture-launch'}});
     if(url.pathname==='/run/snap/note')return route.fulfill({json:{id:'fixture-note'}});
     if(url.pathname==='/run/env/logs')return route.fulfill({json:{id:'fixture-logs'}});
     if(url.pathname.startsWith('/chat/'))return route.fulfill({body:'Fixture agent reply.'});
     throw new Error('Unexpected write blocked: '+url.pathname);
   }
   return route.fallback();
 });
 await page.goto(base+'/worlds');
 const forkHref=await page.locator('a[href^="/fork/"]').first().getAttribute('href');
 const sid=forkHref.split('/').pop();
 await page.route('**/runs/fixture-build',r=>r.fulfill({body:'Built fixture\nUI_WORLD_ROOT:'+sid+'\n[exit 0]\n'}));
 await page.route('**/runs/fixture-launch',r=>r.fulfill({body:'Launched fixture\n[exit 0]\n'}));
 await page.route('**/runs/fixture-note',r=>r.fulfill({body:'Saved fixture note\n[exit 0]\n'}));
 await page.route('**/runs/fixture-logs',r=>r.fulfill({body:'Fixture raw log output\n[exit 0]\n'}));
 await page.goto(base+'/environments');
 const envHref=await page.locator('a[href^="/watch/"]').first().getAttribute('href');
 const env=decodeURIComponent(envHref.split('/').pop());
 await page.route('**/info/*',r=>r.fulfill({json:{Status:'dormant',Runtime:'12m',Started:'2026-09-14'}}));
 await page.route('**/budget/*',r=>r.fulfill({json:{used:.4,limit:2}}));
 let agent;
 await page.route('**/views/*',r=>r.fulfill({json:{views:[['feed',[]],['board',[]],['budget',[]],['GM (spoilers)',[]],[agent||'a12345',[(agent||'a12345')+':thoughts',(agent||'a12345')+':scratchpad']]]}}));
 await page.route('**/stream/**',r=>r.fulfill({contentType:'application/x-ndjson',body:JSON.stringify({ts:'2026-09-14T12:00:00Z',kind:'message',who:agent||'world',text:'Fixture observation: a public message.'})+'\n'}));
 await page.goto(base+'/scenarios');
 await page.getByRole('searchbox').fill('support_desk');
 assert.equal(await page.locator('.scenario-card:visible').count(),2);
 await page.goto(base+'/scenarios/support_desk');
 assert.equal(await page.getByRole('link',{name:/View scenario on GitHub/}).getAttribute('href'),'https://github.com/sfgeekgit/agentspace/tree/main/scenarios/support_desk');
 await page.goto(base+'/new/pd');
 await page.locator('[name=rounds]').fill('7');
 await page.getByRole('button',{name:/Configure agents/}).click();
 assert.equal(JSON.parse(await page.locator('[name=params]').inputValue()).rounds,7);
 await page.locator('[name=model_0]').fill('fixture/model');
 await page.locator('#copyrow').click();
 assert.equal(await page.locator('[name=model_1]').inputValue(),'fixture/model');
 await page.locator('[name=world_name]').fill('browser_fixture');
 await page.getByRole('button',{name:/Build world root/}).click();
 await page.locator('#build-next a').waitFor();
 assert.equal(writes[0].fields.world_name,'browser_fixture');
 assert.equal(writes[0].fields.model_1,'fixture/model');
 await page.locator('#build-next a').click();
 assert.equal(new URL(page.url()).pathname,forkHref);
 await page.locator('[name=new_env_name]').fill(env);
 await page.locator('[name=budget_usd]').fill('3.25');
 await page.locator('[name=kick]').selectOption('off');
 await page.getByRole('button',{name:/Launch environment/}).click();
 await page.waitForURL(base+envHref);
 assert.equal(writes[1].fields.budget_usd,'3.25');
 assert.equal(writes[1].fields.kick,'off');
 agent=await page.locator('[data-agent]').first().getAttribute('data-agent');
 await page.getByRole('button',{name:'Reconnect',exact:true}).click();
 await page.locator('#pane .ev').waitFor();
 await page.screenshot({path:'.preview-artifacts/observatory.png',fullPage:true});
 assert.match(await page.locator('#pane').textContent(),/Fixture observation/);
 assert.equal(await page.locator('.sidebar').isVisible(),false);
 assert.equal(await page.locator('#agents [data-agent]').first().isVisible(),true);
 assert.equal(await page.locator('#actions').getByRole('button',{name:'Start',exact:true}).isDisabled(),true);
 assert.equal(await page.locator('#actions').getByRole('button',{name:'Sleep',exact:true}).isDisabled(),true);
 assert.equal(await page.locator('#actions').getByRole('button',{name:'Wake',exact:true}).isEnabled(),true);
 const boxes=await page.evaluate(()=>Object.fromEntries(['agents','pane','side'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return [id,{x:r.x,right:r.right,height:r.height}]})));
 assert.ok(boxes.agents.right<=boxes.pane.x+1 && boxes.pane.right<=boxes.side.x+1,'Agents, stream, and budget are side by side');
 assert.ok(boxes.pane.height>600,'Logs fill the viewport');
 await page.getByRole('tab',{name:'board',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'board',exact:true}).getAttribute('aria-selected'),'true');
 await page.getByRole('tab',{name:'GM (spoilers)',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'GM (spoilers)',exact:true}).getAttribute('aria-selected'),'true');
 // Both splitters work from the keyboard, and remembered widths survive reloads.
 const divider=page.getByRole('separator',{name:'Resize agent list'});
 const before=await page.locator('#agents').evaluate(n=>n.getBoundingClientRect().width);
 await divider.focus();await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('#agents').evaluate(n=>n.getBoundingClientRect().width),before+20);
 await page.reload();
 assert.equal(await page.locator('#agents').evaluate(n=>n.getBoundingClientRect().width),before+20);
 const rightDivider=page.getByRole('separator',{name:'Resize budget and output'});
 const width=await page.locator('#side').evaluate(n=>n.getBoundingClientRect().width);
 const handle=await rightDivider.boundingBox();await page.mouse.move(handle.x+3,handle.y+30);await page.mouse.down();await page.mouse.move(handle.x-27,handle.y+30);await page.mouse.up();
 assert.ok(await page.locator('#side').evaluate(n=>n.getBoundingClientRect().width)>width);
 await page.locator('#views [role=tab]').first().waitFor();
 await page.locator('[data-agent]').first().click();
 await page.locator('#chat').waitFor({state:'visible'});
 await page.getByRole('tab',{name:'thoughts',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'thoughts',exact:true}).getAttribute('aria-selected'),'true');
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:'scratchpad',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('[data-agent]').first().getAttribute('aria-pressed'),'true');
 await page.locator('#chat-text').fill('Hello, fixture.');
 await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.getByText('Fixture agent reply.',{exact:false}).waitFor();
 await page.locator('#speed').selectOption('5');
 await page.waitForFunction(()=>document.querySelector('#live').textContent==='Replay complete');
 await page.locator('#actions').getByRole('button',{name:'Logs',exact:true}).click();
 await page.locator('#action-dialog').getByRole('button',{name:'Read raw logs',exact:true}).click();
 await page.locator('#out').getByText('Fixture raw log output',{exact:true}).waitFor();
 assert.equal(await page.locator('#side #activity').count(),1);
 const output=await page.locator('#activity').boundingBox(),logs=await page.locator('#pane').boundingBox();
 assert.ok(output.x>=logs.x+logs.width,'Operation output does not cover the stream');
 assert.equal(await page.getByRole('tab',{name:'scratchpad',exact:true}).getAttribute('aria-selected'),'true');
 await page.getByText('Terminal access',{exact:true}).click();
 assert.match(await page.locator('.terminal-note').textContent(),/python3 zookeeper.py env exec/);
 assert.equal(await page.locator('[data-action="env exec"]').count(),0);
 await page.goto(base+'/snapshots/'+sid);
 await page.getByRole('button',{name:'Add note',exact:true}).click();
 await page.locator('#action-dialog [name=text]').fill('A fixture note.');
 await page.locator('#action-dialog button').filter({hasText:'Add a note'}).click();
 await page.locator('#result-link').getByText('Completed.',{exact:true}).waitFor();
 assert.equal(writes.at(-1).fields.text,'A fixture note.');
 assert.ok(writes.at(-1).fields.snap_ref);
 await page.goto(base+'/tools');
 const exec=page.locator('details').filter({has:page.locator('summary',{hasText:'env exec'})});
 await exec.locator('summary').click();
 assert.equal(await exec.locator('form').count(),0);
 // Check every principal screen at mobile width, including root and snapshot details.
 await page.setViewportSize({width:390,height:844});
 for(const path of ['/','/scenarios','/scenarios/support_desk','/worlds','/worlds/'+sid,'/snapshots/'+sid,'/fork/'+sid,'/environments','/tools','/help','/new/pd','/new/pd/roster?n=2&rounds=5',envHref]){
   await page.goto(base+path);
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
   assert.ok(!overflow,'Page overflow at '+path);
   if(path==='/'||path===envHref)await page.screenshot({path:'.preview-artifacts/'+(path==='/'?'mobile-overview':'mobile-observatory')+'.png',fullPage:true});
 }
 assert.deepEqual(errors,[]);
 console.log('PASS: scenario search and GitHub links; parameter/roster → exact build result → fork → observatory; visible agent cards, view/facet tabs, replay and chat; resizable columns; side output; snapshot notes; terminal-only controls; 13 mobile routes; no browser errors.');
 console.log('All '+writes.length+' writes were intercepted; no real experiment was modified.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
